# Generated by Django 2.2.6 on 2019-12-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicMaterializer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='detect_bpm',
            field=models.BooleanField(default=False, verbose_name='Detect BPM'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='record',
            field=models.BooleanField(default=False, verbose_name='Record Audio'),
        ),
    ]
