# Generated by Django 3.0 on 2019-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicMaterializer', '0002_auto_20191201_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='record',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='bpm_number',
            field=models.CharField(default=120, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='detect_bpm',
            field=models.BooleanField(verbose_name='Detect BPM'),
        ),
    ]
