# Generated by Django 3.0 on 2019-12-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicMaterializer', '0003_auto_20191208_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='bpm_number',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='detect_bpm',
        ),
    ]
