# Generated by Django 3.0 on 2019-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicMaterializer', '0004_auto_20191211_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='apikey',
            field=models.CharField(max_length=500),
        ),
    ]
